sudo: required 
dist: trusty
language: ruby
rvm:
  # - "2.4.3"
  - "2.5.0"
env:
  global:
    - CERTIFICATE=./certs/ruby.pem
    - PASSPHRASE=client11
    - RAVEN_PROTOCOL=https URL=https://localhost:8433
  matrix:
    - DOWNLOAD_URL=https://daily-builds.s3.amazonaws.com/RavenDB-4.0.4-nightly-20180427-0400-linux-x64.tar.bz2
    - DOWNLOAD_URL=https://daily-builds.s3.amazonaws.com/RavenDB-4.0.4-nightly-20180429-0400-linux-x64.tar.bz2
    - DOWNLOAD_URL=https://daily-builds.s3.amazonaws.com/RavenDB-4.0.4-nightly-20180430-0400-linux-x64.tar.bz2
    - DOWNLOAD_URL=https://daily-builds.s3.amazonaws.com/RavenDB-4.0.4-nightly-20180501-0400-linux-x64.tar.bz2
    - DOWNLOAD_URL=https://daily-builds.s3.amazonaws.com/RavenDB-4.0.4-nightly-20180502-0400-linux-x64.tar.bz2
    - DOWNLOAD_URL=https://daily-builds.s3.amazonaws.com/RavenDB-4.0.4-nightly-20180503-0400-linux-x64.tar.bz2
    - DOWNLOAD_URL=https://daily-builds.s3.amazonaws.com/RavenDB-4.0.4-nightly-20180504-0400-linux-x64.tar.bz2
    - DOWNLOAD_URL=https://daily-builds.s3.amazonaws.com/RavenDB-4.0.4-nightly-20180505-0400-linux-x64.tar.bz2
    - DOWNLOAD_URL=https://daily-builds.s3.amazonaws.com/RavenDB-4.0.4-nightly-20180506-0400-linux-x64.tar.bz2
    - DOWNLOAD_URL=https://daily-builds.s3.amazonaws.com/RavenDB-4.0.4-nightly-20180507-0400-linux-x64.tar.bz2
    - DOWNLOAD_URL=https://daily-builds.s3.amazonaws.com/RavenDB-4.0.4-nightly-20180508-0400-linux-x64.tar.bz2
    - DOWNLOAD_URL=https://daily-builds.s3.amazonaws.com/RavenDB-4.0.4-nightly-20180509-0400-linux-x64.tar.bz2
    - DOWNLOAD_URL=https://daily-builds.s3.amazonaws.com/RavenDB-4.0.4-nightly-20180510-0400-linux-x64.tar.bz2
script:
  - bundle exec rake
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libunwind8 wget libicu52 libssl-dev curl unzip gettext libcurl4-openssl-dev zlib1g uuid-dev bzip2 openssl
  - mkdir ./certs; cd ./certs
  - openssl genrsa -out ca.key 2048
  - openssl req -new -x509 -key ca.key -out ca.crt -subj "/C=US/ST=Arizona/L=Nevada/O=RavenDB Test CA/OU=RavenDB test CA/CN=localhost/emailAddress=ravendbca@example.com"
  - openssl genrsa -out localhost.key 2048
  - openssl req -new  -key localhost.key -out localhost.csr -subj "/C=US/ST=Arizona/L=Nevada/O=RavenDB Test/OU=RavenDB test/CN=localhost/emailAddress=ravendb@example.com"
  - openssl x509 -req -extensions ext -extfile ../spec/fixtures/cert/test_cert.conf -in localhost.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out localhost.crt
  - cat localhost.key localhost.crt > ruby.pem
  - openssl pkcs12 -passout pass:$PASSPHRASE -export -out server.pfx -inkey localhost.key -in localhost.crt
  - sudo cp ca.crt /usr/local/share/ca-certificates/ca.crt
  - sudo update-ca-certificates
  - cd ..  
  - wget -O RavenDB.tar.bz2 "$DOWNLOAD_URL"
  - tar xvjf RavenDB.tar.bz2
  - cp ./spec/fixtures/cert/test_settings_$RAVEN_PROTOCOL.json ./RavenDB/Server/settings.json
  - export RAVEN_PFX=$PWD/certs/server.pfx
  - sed -i 's@PFX@'"$RAVEN_PFX"'@' ./RavenDB/Server/settings.json
  - sed -i s/PASS/$PASSPHRASE/ ./RavenDB/Server/settings.json
  - ./RavenDB/Server/Raven.Server --non-interactive &
  - sleep 1
